[package]
name = "package_selector"
version = "0.1.0"
edition = "2024"

[dependencies]
bdk_chain = { path = "../../bdk/crates/chain", version = "0.22.0" }
bitcoin = { version = "0.32.5", features = ["rand-std"] }
